### ISSUE TITLE
Organisation ownership transfer

### ISSUE THREAD

**Issue by mwala-zm** [yshmarov/moneygun#151]
It would be great to have a feature that allows organisation owners to transfer ownership to any current member of the organisation. Same way whatsapp allows users to update who the current owner of the group is.

**Comment by yshmarov** [comment]
That sounds like a perfect feature to add! I'll draft a PR tonight.

**Comment by yshmarov** [comment]
@mwala-zm I've got a draft PR ⬆️

**Comment by petrokoriakin1** [comment]
omg! the only good issue?

**Comment by yshmarov** [comment]
@mwala-zm merged! 
Thanks for suggesting the feature.
Feel free to share more ideas!

**Comment by yshmarov** [comment]
Note: 

As a next step, we could send old & new owners email confirmation about transfer. Not important now.

**Comment by mwala-zm** [comment]
Glad I could share my ideas. Thank you for creating this project, it's helping me understand the concept of multi-tenancy.
