### ISSUE TITLE
Steal GitLab's permission matrix

### ISSUE THREAD

**Issue by petrokoriakin1** [yshmarov/moneygun#154]
https://docs.gitlab.com/ee/user/permissions.html

**Comment by yshmarov** [comment]
Thanks for the suggestion!
I want to keep it as minimal as possible for now.
People building on top of it can add their own permissions

**Comment by petrokoriakin1** [comment]
heh. so then this can be implemented as an engine extension. Maybe
separately in connections with `acts_as_tenant`
